name: Run Integration Tests

on:
  pull_request:

jobs:
  test-cedar-policy:
    name: Test Rust implementation
    uses: cedar-policy/cedar/.github/workflows/run_integration_tests_reusable.yml@khieta/ci-nit

  test-cedar-spec:
    name: Test Lean implementation
    uses: cedar-policy/cedar-spec/.github/workflows/run_integration_tests_reusable.yml@khieta/ci-nit