name: Run Integration Tests

on:
  pull_request:

jobs:
  get-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        shell: bash
        # The workflow is triggered by pull_request so we use `GITHUB_BASE_REF`
        run: echo "branch_name=${GITHUB_BASE_REF}" >> $GITHUB_OUTPUT
        id: get_branch_name
    outputs:
      branch_name: ${{ steps.get_branch_name.outputs.branch_name }}

  test-cedar-policy:
    name: Test Rust implementation
    needs: get-branch-name
    uses: cedar-policy/cedar/.github/workflows/run_integration_tests_reusable.yml@main
    with:
      cedar_integration_tests_ref: ${{ github.ref }}
      cedar_policy_ref: ${{ needs.get-branch-name.outputs.branch_name }}

  test-cedar-spec:
    name: Test Lean implementation
    needs: get-branch-name
    uses: cedar-policy/cedar-spec/.github/workflows/run_integration_tests_reusable.yml@main
    with:
      cedar_integration_tests_ref: ${{ github.ref }}
      cedar_spec_ref: ${{ needs.get-branch-name.outputs.branch_name }}
  
  inspect-corpus:
    name: Print out corpus statistics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ./scripts
        run: pip3 install -r requirements.txt
      - name: Generate table
        working-directory: ./scripts
        run: python3 get_corpus_stats.py ../corpus-tests.tar.gz
